spring.application.name=backend
openwebcamdb.api.key=${OPENWEBCAMDB_API_KEY}
frontend.url=${MY_FRONTEND_URL}
application.name=${MY_APPLICATION_NAME}
contact.email=${MY_CONTACT_EMAIL}
sendgrid.api.key=${SENDGRID_API_KEY}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Make the backend listen on all network interfaces
server.address=0.0.0.0
server.port=8080

spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m,recordStats
logging.level.org.apache.coyote.http11.Http11Processor=ERROR
